services:
  dev:
    build:
      context: ..
      dockerfile: .ai/Dockerfile
    container_name: ${AI_CONTAINER_NAME:-ai_container_name}
    working_dir: /workspace
    volumes:
      - ${WORKTREE}:/workspace
      - ${HOME}/.ai:/host/.ai:ro
      # Legacy path, no longer needed
    # - ${HOME}/.cc:/host/.cc:ro  # For backward compatibility
    environment:
      - AWS_CONTAINER_CREDENTIALS_FULL_URI=http://localhost:55491/
      - CLAUDE_CODE_USE_BEDROCK=${CLAUDE_CODE_USE_BEDROCK}
      - AWS_REGION=${AWS_REGION}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT:-1}
          memory: ${MEM_LIMIT:-2g}