services:
  dev:
    build: .
    container_name: ${CC_CONTAINER_NAME}
    working_dir: /workspace
    volumes:
      - ${WORKTREE}:/workspace
      - ${HOME}/.cc:/host/.cc:ro
    environment:
      - AWS_CONTAINER_CREDENTIALS_FULL_URI=${IMDS_URL}
      - AWS_CONTAINER_AUTHORIZATION_TOKEN=${AWS_CONTAINER_AUTHORIZATION_TOKEN:-}
      - CLAUDE_CODE_USE_BEDROCK=${CLAUDE_CODE_USE_BEDROCK}
      - ANTHROPIC_MODEL=${ANTHROPIC_MODEL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT:-1}
          memory: ${MEM_LIMIT:-2g}