#!/usr/bin/env bash
set -euo pipefail

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Function to update .gitignore file
update_gitignore() {
  local target_dir="$1"
  local gitignore_path="$target_dir/.gitignore"
  
  # Create .gitignore if it doesn't exist
  if [[ ! -f "$gitignore_path" ]]; then
    echo "# Automatically generated by claude-dev-sandbox installer" > "$gitignore_path"
    echo "Creating .gitignore file"
  fi
  
  # Add entries to .gitignore if they don't already exist
  for entry in ".cc/" ".envrc"; do
    if ! grep -q "^$entry$" "$gitignore_path"; then
      echo "$entry" >> "$gitignore_path"
      echo "✔ Added $entry to .gitignore"
    fi
  done
}

# Process command line arguments
USE_DIRENV=1
TARGET=""

for arg in "$@"; do
  case "$arg" in
    --no-direnv)
      USE_DIRENV=0
      ;;
    *)
      if [[ -z "$TARGET" ]]; then
        TARGET="$arg"
      fi
      ;;
  esac
done

# Check if target is provided
if [[ -z "$TARGET" ]]; then
  echo "Usage: install.sh [--no-direnv] /path/to/repo"
  exit 1
fi

# Validate target is a git repo
[[ ! -d "$TARGET/.git" ]] && { echo "✖ $TARGET is not a Git repo"; exit 1; }

mkdir -p "$TARGET/.cc/scripts"
cp -R "$SCRIPT_DIR/scripts"/* "$TARGET/.cc/scripts/"
cp "$SCRIPT_DIR/scripts/templates/.ccenv.example" "$TARGET/.cc/.ccenv.example"

# Set the USE_DIRENV configuration value
if [[ -f "$TARGET/.cc/.ccenv" ]]; then
  # Update existing file if it exists
  if grep -q "^USE_DIRENV=" "$TARGET/.cc/.ccenv"; then
    sed -i.bak "s/^USE_DIRENV=.*/USE_DIRENV=$USE_DIRENV/" "$TARGET/.cc/.ccenv"
    rm -f "$TARGET/.cc/.ccenv.bak"
  else
    echo "USE_DIRENV=$USE_DIRENV" >> "$TARGET/.cc/.ccenv"
  fi
else
  # Create new file if it doesn't exist
  echo "USE_DIRENV=$USE_DIRENV" > "$TARGET/.cc/.ccenv"
fi

# Handle PATH integration based on direnv preference
if [[ "$USE_DIRENV" -eq 1 ]] && command -v direnv &> /dev/null; then
    # Use direnv if enabled and available
    echo 'export PATH="$PATH:$(git rev-parse --show-toplevel)/.cc/scripts"' >> "$TARGET/.envrc" || true
    echo "✔ Added scripts to PATH via direnv (.envrc)"
else
    # Don't use direnv - provide manual PATH instructions
    SCRIPTS_PATH="$TARGET/.cc/scripts"
    echo "ℹ️ Using non-direnv mode. To use the cc-* commands from anywhere:"
    echo "  Add the scripts to your PATH manually:"
    echo "    export PATH=\"\$PATH:$SCRIPTS_PATH\""
fi

# Update .gitignore to exclude Claude dev files
update_gitignore "$TARGET"

echo "✔ Claude dev scripts installed in $TARGET"
echo "ℹ️ Run the commands from the repository root or add the scripts to your PATH"